"""
Loads and prepares issue-report data for training/evaluation.

Works against either:
  - the real NLBSE'23 CSVs (after running data/download_dataset.sh), or
  - the bundled synthetic sample CSVs (data/sample_issues_{train,test}.csv),
    generated by data/generate_sample_data.py, used when real data isn't
    available (e.g. this sandbox has no network access to the dataset host).

Both sources share the same schema: label, id, title, body, author_association.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd

LABELS = ["bug", "feature", "question", "documentation"]

DEFAULT_TRAIN_CSV = Path(__file__).resolve().parent.parent / "data" / "sample_issues_train.csv"
DEFAULT_TEST_CSV = Path(__file__).resolve().parent.parent / "data" / "sample_issues_test.csv"


@dataclass
class Dataset:
    text: pd.Series
    label: pd.Series


def _combine_text(df: pd.DataFrame) -> pd.Series:
    """Concatenate title + body into a single text field for vectorization."""
    title = df["title"].fillna("")
    body = df["body"].fillna("")
    return (title + " " + body).str.strip()


def load_csv(path: str | Path) -> pd.DataFrame:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Dataset file not found: {path}. Run data/generate_sample_data.py for a local "
            f"dev dataset, or data/download_dataset.py (on a machine with network access) "
            f"for the real NLBSE'23 data."
        )
    df = pd.read_csv(path)

    if "label" not in df.columns and "labels" in df.columns:
        df = df.rename(columns={"labels": "label"})

    missing = {"label", "title", "body"} - set(df.columns)
    if missing:
        raise ValueError(f"Dataset {path} is missing required columns: {missing}")
    df = df[df["label"].isin(LABELS)].dropna(subset=["title"]).reset_index(drop=True)
    return df


def load_dataset(path: str | Path) -> Dataset:
    df = load_csv(path)
    return Dataset(text=_combine_text(df), label=df["label"])


def load_train_test(
    train_path: str | Path = DEFAULT_TRAIN_CSV,
    test_path: str | Path = DEFAULT_TEST_CSV,
) -> tuple[Dataset, Dataset]:
    return load_dataset(train_path), load_dataset(test_path)


if __name__ == "__main__":
    train, test = load_train_test()
    print(f"Train: {len(train.text)} rows, label counts:\n{train.label.value_counts()}")
    print(f"Test:  {len(test.text)} rows, label counts:\n{test.label.value_counts()}")
